### ISSUE TITLE
Deploy_03 / "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#248]
### 現状
```
http://Elastic IP
```
にアクセスすると
```
 "We're sorry, but something went wrong."
```

**Comment by hasyrails** [comment]
### production.logを確認
```
 [2021-04-17T05:23:18.617048 #31541] DEBUG -- : [32751b31-290b-4671-8941-1ceb9a3ffd89]    (0.4ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
I, [2021-04-17T05:23:18.642385 #31541]  INFO -- : [32751b31-290b-4671-8941-1ceb9a3ffd89]   Rendering top/index.html.erb within layouts/application
I, [2021-04-17T05:23:18.644583 #31541]  INFO -- : [32751b31-290b-4671-8941-1ceb9a3ffd89]   Rendered layouts/_flash_message.html.erb (Duration: 0.7ms | Allocations: 163)
I, [2021-04-17T05:23:18.644748 #31541]  INFO -- : [32751b31-290b-4671-8941-1ceb9a3ffd89]   Rendered top/index.html.erb within layouts/application (Duration: 2.3ms | Allocations: 798)
I, [2021-04-17T05:23:18.646246 #31541]  INFO -- : [32751b31-290b-4671-8941-1ceb9a3ffd89] Completed 500 Internal Server Error in 43ms (ActiveRecord: 21.4ms | Allocations: 6474)
F, [2021-04-17T05:23:18.646930 #31541] FATAL -- : [32751b31-290b-4671-8941-1ceb9a3ffd89]   
[32751b31-290b-4671-8941-1ceb9a3ffd89] ActionView::Template::Error (Webpacker can't find application in /var/www/rails/favimo/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/js/application-5a2be64bc89c4f42b27a.js",
  "application.js.map": "/packs/js/application-5a2be64bc89c4f42b27a.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-5a2be64bc89c4f42b27a.js"
      ],
      "js.map": [
        "/packs/js/application-5a2be64bc89c4f42b27a.js.map"
      ]
    }
  }
}
):
[32751b31-290b-4671-8941-1ceb9a3ffd89]     10:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
[32751b31-290b-4671-8941-1ceb9a3ffd89]     11:     <%= javascript_pack_tag 'application'%>
[32751b31-290b-4671-8941-1ceb9a3ffd89]     12:   
[32751b31-290b-4671-8941-1ceb9a3ffd89]     13:     <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
[32751b31-290b-4671-8941-1ceb9a3ffd89]     14:     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
[32751b31-290b-4671-8941-1ceb9a3ffd89]     15: 
[32751b31-290b-4671-8941-1ceb9a3ffd89]     16: 
[32751b31-290b-4671-8941-1ceb9a3ffd89]   
[32751b31-290b-4671-8941-1ceb9a3ffd89] app/views/layouts/application.html.erb:13
I, [2021-04-17T05:23:19.051709 #31541]  INFO -- : [34847ad4-17ed-4af1-9c0b-c5ab787f93ce] Started GET "/favicon.ico" for 127.0.0.1 at 2021-04-17 05:23:19 +0000
F, [2021-04-17T05:23:19.052241 #31541] FATAL -- : [34847ad4-17ed-4af1-9c0b-c5ab787f93ce]   
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce]   
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] actionpack (6.0.3.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] actionpack (6.0.3.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] railties (6.0.3.6) lib/rails/rack/logger.rb:37:in `call_app'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] railties (6.0.3.6) lib/rails/rack/logger.rb:26:in `block in call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] activesupport (6.0.3.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] activesupport (6.0.3.6) lib/active_support/tagged_logging.rb:28:in `tagged'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] activesupport (6.0.3.6) lib/active_support/tagged_logging.rb:80:in `tagged'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] railties (6.0.3.6) lib/rails/rack/logger.rb:26:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] actionpack (6.0.3.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] actionpack (6.0.3.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] activesupport (6.0.3.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] actionpack (6.0.3.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] actionpack (6.0.3.6) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] railties (6.0.3.6) lib/rails/engine.rb:527:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] puma (4.3.7) lib/puma/configuration.rb:228:in `call'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] puma (4.3.7) lib/puma/server.rb:472:in `process_client'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] puma (4.3.7) lib/puma/server.rb:328:in `block in run'
[34847ad4-17ed-4af1-9c0b-c5ab787f93ce] puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```

**Comment by hasyrails** [comment]
### webpacker.ymlを修正
``` yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
-  resolved_paths: []
+  resolved_paths: ['app/javascript/images', 'app/assets/images']

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: false

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```
